// Generated by scripts/prepare_visual_assets.py; changes invalidate visual manifests.
export const VISUAL_SOURCE_HASH = "f905dbb8702e272ba66b9779a01dff65dea7a61e2b0836c80dd00dae92b8b28e";
export const VISUAL_FILE_HASHES = Object.freeze({
  "visual-assets.js": "4d3596f21c5e441a20d5ff260d8bb9bed89b9ff149807ce325ad533d8b57e7cd",
  "visual-inventory.js": "b75f6ba940691385453f013fe0967538125f8be0c2ad20a244f457538f8ae678",
  "visual-renderer.js": "7ef7eff17836d178d0277ff1416bd14984f01df434c87f645464d95dd052f153",
  "visual-layers.js": "d08fbcae12b20cfc13e5253c248c83a37f738194801044dbc572915262aba66c",
  "visual-board-scene.js": "ee23ab3ebf078f4ba5b90793a2cd3042a351c1d074f7dd8cb9906423a6067c4f",
  "vendor/three.module.js": "e2b5ee6bccd38fd6d8a2428546b83c5f2426d84b152ef82be8055556e3b40eb6",
  "vendor/three.core.min.js": "61ba0df005b05991361d040d8ff670e1aadfd0ce7aeebd1fdb0725957a8957de",
  "vendor/THREE-LICENSE.txt": "bfe119ea4fd413f5f7ca3fcd63adb0c4a073ed39daa2fe7d3e6b769e21272601",
  "component-library/data/chip2t.json": "3598c7844ba46889e517aea062023e8fd5a53d2daa773b1109bd0a17a56e1915",
  "component-library/generators/chip-2t.js": "4ded35e976d9919913bd0ca1873d7b1b1bdd03171efb2a86e7dce6dfb7c187f7",
  "component-library/materials.js": "e46e7a1f879e97403a4035d708a4321282f60cdba645a73af13511460d4496ac",
  "component-library/preview/index.html": "515001158e473ea8fc8d293d9f9393a260a2a8c1a1695859d854061beddf00b6",
  "component-library/preview/model-preview.js": "7d9d6506a55c2b579f11eceebd892a7d008009bec37ee4bd936be28e43f58366",
  "component-library/preview/preview.css": "2ab9212efc2935d1ee21faa7991fc3925d59e4d0276af6c9d73b7f8e9b7c3f2f",
  "component-library/preview/preview.js": "05d6c3b59dd3f62ab3f8970de46c69130f25a82e7000083ef414287d3492d0bf",
  "component-library/registry.js": "0f67c3db6aceea71868d398e47c42d7ed8fda220512936279f3ed9cb03253186",
  "component-library/transforms.js": "3ee469f3884627809c8a557b120eb7b48cb56e760e9a94fe4823d7ebb7f1252c",
  "component-library/validate.js": "c3665e607c53d51d5e91d08e6a88c4726dbfc5d398bf6be1cb54c61d4fd921e8"
});
