// Generated by scripts/prepare_visual_assets.py; changes invalidate visual manifests.
export const VISUAL_SOURCE_HASH = "99a4deb128f244176ac249bea5894ed2cb7555bd62d00e066286b63e6ed5b706";
export const VISUAL_FILE_HASHES = Object.freeze({
  "visual-assets.js": "4d3596f21c5e441a20d5ff260d8bb9bed89b9ff149807ce325ad533d8b57e7cd",
  "visual-inventory.js": "b75f6ba940691385453f013fe0967538125f8be0c2ad20a244f457538f8ae678",
  "visual-renderer.js": "4a1223dcf098dd2720b03151e5a855bd20f9fc7ae620eebb709fa722021fce47",
  "visual-layers.js": "d08fbcae12b20cfc13e5253c248c83a37f738194801044dbc572915262aba66c",
  "visual-board-scene.js": "ee23ab3ebf078f4ba5b90793a2cd3042a351c1d074f7dd8cb9906423a6067c4f",
  "vendor/three.module.js": "e2b5ee6bccd38fd6d8a2428546b83c5f2426d84b152ef82be8055556e3b40eb6",
  "vendor/three.core.min.js": "61ba0df005b05991361d040d8ff670e1aadfd0ce7aeebd1fdb0725957a8957de",
  "vendor/THREE-LICENSE.txt": "bfe119ea4fd413f5f7ca3fcd63adb0c4a073ed39daa2fe7d3e6b769e21272601"
});
