import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import * as THREE from '../vendor/three.module.js';import {createCompletionLibrary,createCompletionComponent} from '../component-library/completion-registry.js';
const data=JSON.parse(readFileSync(new URL('../component-library/data/completion-d.json',import.meta.url))),lib=createCompletionLibrary(data);
const cases=[[44,2,.71,0,1.42,1.8,1.12,1.02,0,0],[45,2,2.95,0,5.9,8.4,6.7,2.8,0,0],[46,2,2.5,0,5,7,5.8,4.8,0,0],[48,2,2.5,0,5,8.7,8.7,12,0,2.6],[49,2,4.064,0,8.128,21.84,21.84,11.43,1.57,2.6],[50,4,3.81,3.11,6.22,10,8.7,6.5,0,0],[51,4,5,2.25,4.5,15.8,7.8,18,0,2.5],[52,6,5.335,4.75,4.75,17.8,20.6,18.8,0,2.6],[53,12,14.62,6.25,2.5,32.31,27.03,13.69,0,2.6],[54,3,6.35,0,6.35,17.2,9.53,20.4,0,2.6],[55,16,5.08,4.445,1.27,10.76,12.7,6.8,0,0]];
const near=(a,b)=>assert.ok(Math.abs(a-b)<3e-5,`${a} != ${b}`);
function sig(g){const a=[];g.traverse(m=>{if(m.isMesh)a.push([m.name,Array.from(m.geometry.attributes.position.array),m.position.toArray(),m.material.name,m.isInstancedMesh?Array.from(m.instanceMatrix.array):null,m.userData]);});return createHash('sha256').update(JSON.stringify([a,g.userData])).digest('hex');}
for(const [n,count,x,y,pitch,W,L,H,z,tail] of cases)for(const lod of ['LOD0','LOD1','LOD2'])test(`OHM-${String(n).padStart(3,'0')} ${lod} contacts/pin1/order/bounds/determinism`,()=>{
 const id=`OHM-${String(n).padStart(3,'0')}`,g=createCompletionComponent(lib,id,{lod}),cs=g.userData.contacts;assert.equal(cs.length,count);
 const xy=count<=3?Array.from({length:count},(_,i)=>[-x+pitch*i,0]):[...Array.from({length:count/2},(_,i)=>[-x,y-pitch*i]),...Array.from({length:count/2},(_,i)=>[x,-y+pitch*i])];
 cs.forEach((c,i)=>{assert.equal(c.terminal,String(i+1));near(c.center_mm[0],xy[i][0]);near(c.center_mm[1],xy[i][1]);near(c.center_mm[2],0);});
 g.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(g);near(b.max.x-b.min.x,W);near(b.max.y-b.min.y,L);near(b.max.z,H+z);near(b.min.z,-tail);
 g.traverse(m=>{if(m.isMesh){assert.ok(m.material.name.startsWith('MAT_'));assert.ok(Array.from(m.geometry.attributes.position.array).every(Number.isFinite));}});assert.equal(sig(g),sig(createCompletionComponent(lib,id,{lod})));
 if(g.userData.parameters.mark_pin1){const mark=g.getObjectByName('pin1-mark');assert.ok(mark.position.x<0);if(count>=4)assert.ok(mark.position.y>0);}
});
test('Group D raw source status and hashing',()=>{const source=readFileSync(new URL('../../../PCB_COMPONENT_3D_LIBRARY_SPEC.md',import.meta.url));assert.equal(data.source_spec_sha256,createHash('sha256').update(source).digest('hex'));for(const r of data.components){const raw=source.toString().split(`# [${r.id}]`)[1].split(/\n# \[|\n## PROPOSED ADDITIONS/)[0].match(/```yaml\s*\n([\s\S]*?)\n```/)[1];assert.equal(r.status,raw.match(/^status: (\w+)/m)[1]);assert.equal(r.source.yaml_sha256,createHash('sha256').update(raw).digest('hex'));assert.equal(r.library_metadata.implementation_status,'IMPLEMENTED');assert.ok(r.library_metadata.uncertain_values.length);}});
test('Flyback convention does not overwrite unknown source pin1 or admit a footprint',()=>{const r=lib.records['OHM-053'],g=createCompletionComponent(lib,r.id);assert.equal(r.terminals.pin1_xy_mm,'RESEARCH_REQUIRED');assert.deepEqual(g.userData.contacts[0].center_mm,[-14.62,6.25,0]);assert.equal(g.userData.footprint_binding,null);assert.ok(r.library_metadata.conflicts.some(c=>c.code==='FLYBACK_PIN1_DERIVATION'));assert.ok(g.getObjectByName('winding-tape'));});
test('Toroid aperture remains open at every LOD',()=>{for(const lod of ['LOD0','LOD1','LOD2']){const g=createCompletionComponent(lib,'OHM-049',{lod});g.updateMatrixWorld(true);assert.equal(new THREE.Raycaster(new THREE.Vector3(0,0,30),new THREE.Vector3(0,0,-1)).intersectObject(g,true).length,0);}});
