import math,subprocess,re,sys
def design(f0=869e6,bw=8e6,Qu=450,R0=50):
    g=[1.5963,1.0967,1.5963]  # Chebyshev 0.5 dB, n=3 (Matthaei/Young/Jones tables)
    w0=2*math.pi*f0; d=bw/f0
    Ls1=g[0]*R0/(d*w0); Cs1=1/(w0*w0*Ls1)
    Cp=g[1]/(R0*d*w0);  Lp=1/(w0*w0*Cp)
    Ls3=g[2]*R0/(d*w0); Cs3=1/(w0*w0*Ls3)
    R=lambda L: w0*L/Qu
    return dict(Ls1=Ls1,Cs1=Cs1,Cp=Cp,Lp=Lp,Ls3=Ls3,Cs3=Cs3,Rs1=R(Ls1),Rp=R(Lp),Rs3=R(Ls3))
def lib(f0=869e6,bw=8e6,il_db=4.5,R0=50):
    v=design(f0,bw,1e12)
    K=10**(il_db/20); rsh=R0*(K+1)/(K-1); rse=R0*(K*K-1)/(2*K)
    s="* OHMNI SAW band-pass L1 behavioural: lossless 3-pole Chebyshev (0.5 dB ripple) + matched pi attenuator for flat insertion loss; 50 ohm; generated by gen_saw_R8.py\n"
    s+=f"* f0={f0} bw(passband, ripple edges)={bw} il_db={il_db} (pad Rshunt={rsh:.4f} Rseries={rse:.4f})\n.subckt ohm_saw in out gnd\n"
    s+=f"Rp1 in gnd {rsh:.6e}\nRps in p2 {rse:.6e}\nRp2 p2 gnd {rsh:.6e}\n"
    s+=f"Ls1 p2 a1 {v['Ls1']:.6e}\nCs1 a1 n1 {v['Cs1']:.6e}\n"
    s+=f"Lp n1 gnd {v['Lp']:.6e}\nCp n1 gnd {v['Cp']:.6e}\n"
    s+=f"Ls3 n1 c1 {v['Ls3']:.6e}\nCs3 c1 out {v['Cs3']:.6e}\n.ends ohm_saw\n"
    return s
if __name__=='__main__':
    open('ohm_saw.lib','w').write(lib())
