"""Ohmni domain layer.

This package must not import infrastructure. No HTTP clients, no subprocess
calls, no file formats belonging to external tools, no LLM SDKs. Everything here
is pure data and pure functions, so the business rules can be tested without a
single external dependency (REPO_STRUCTURE.md, dependency direction).

``tests/test_architecture.py`` enforces this mechanically.
"""

from .circuit import (
    CircuitComponent,
    CircuitIR,
    CircuitPatch,
    CircuitPatchOp,
    ConstraintKind,
    DesignConstraint,
    ExternalSource,
    ExternalSourceKind,
    Net,
    NetKind,
    PinRef,
)
from .component import (
    DRIVING_TYPES,
    I2C_BUS_ROLES,
    MUST_NOT_FLOAT_ROLES,
    PASSIVE_CATEGORIES,
    PUSH_PULL_DRIVERS,
    ComponentCategory,
    ComponentSpec,
    DecouplingRule,
    DesignRule,
    I2CAddressOption,
    Interface,
    LedSpec,
    Lifecycle,
    PackageOption,
    PinElectricalType,
    PinRole,
    PinSpec,
    RegulatorSpec,
    ResolvedPinBehavior,
    SupplyRail,
    resolve_pin_behavior,
)
from .document import (
    DatasheetDocument,
    DatasheetIdentity,
    DocumentFingerprint,
    DocumentMetadata,
    DocumentPage,
    DocumentRegion,
    DocumentSpan,
)
from .events import (
    Alternative,
    DecisionRecord,
    EngineeringEvent,
    EngineeringNotebook,
    EventKind,
    Lesson,
)
from .evidence import (
    Claim,
    ClaimStatus,
    DocumentRef,
    Evidence,
    EvidenceKind,
    SubsystemStatus,
    assumed_evidence,
    calculated_evidence,
    catalog_evidence,
    datasheet_evidence,
    status_rank,
)
from .requirements import (
    FunctionalRequirement,
    RequirementsSpec,
    SafetyDomain,
)
from .units import (
    REL_TOL,
    Quantity,
    QuantityParseError,
    Unit,
    UnitMismatchError,
    ValueRange,
    parse_quantity,
)
from .verification import (
    BLOCKING_SEVERITIES,
    RuleCategory,
    RuleOutcome,
    RuleResult,
    Severity,
    VerificationFinding,
    VerificationReport,
    severity_rank,
)

__all__ = [
    "BLOCKING_SEVERITIES",
    "DRIVING_TYPES",
    "I2C_BUS_ROLES",
    "MUST_NOT_FLOAT_ROLES",
    "PASSIVE_CATEGORIES",
    "PUSH_PULL_DRIVERS",
    "REL_TOL",
    "Alternative",
    "CircuitComponent",
    "CircuitIR",
    "CircuitPatch",
    "CircuitPatchOp",
    "Claim",
    "ClaimStatus",
    "ComponentCategory",
    "ComponentSpec",
    "ConstraintKind",
    "DatasheetDocument",
    "DatasheetIdentity",
    "DecisionRecord",
    "DecouplingRule",
    "DesignConstraint",
    "DesignRule",
    "DocumentFingerprint",
    "DocumentMetadata",
    "DocumentPage",
    "DocumentRef",
    "DocumentRegion",
    "DocumentSpan",
    "EngineeringEvent",
    "EngineeringNotebook",
    "EventKind",
    "Evidence",
    "EvidenceKind",
    "ExternalSource",
    "ExternalSourceKind",
    "FunctionalRequirement",
    "I2CAddressOption",
    "Interface",
    "LedSpec",
    "Lesson",
    "Lifecycle",
    "Net",
    "NetKind",
    "PackageOption",
    "PinElectricalType",
    "PinRef",
    "PinRole",
    "PinSpec",
    "Quantity",
    "QuantityParseError",
    "RegulatorSpec",
    "RequirementsSpec",
    "ResolvedPinBehavior",
    "RuleCategory",
    "RuleOutcome",
    "RuleResult",
    "SafetyDomain",
    "Severity",
    "SubsystemStatus",
    "SupplyRail",
    "Unit",
    "UnitMismatchError",
    "ValueRange",
    "VerificationFinding",
    "VerificationReport",
    "assumed_evidence",
    "calculated_evidence",
    "catalog_evidence",
    "datasheet_evidence",
    "parse_quantity",
    "resolve_pin_behavior",
    "severity_rank",
    "status_rank",
]
