"""Refresh local pinned Three modules and deterministic visual-source fingerprints."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "apps" / "web"


def main() -> None:
    package = WEB / "node_modules" / "three"
    version = json.loads((package / "package.json").read_text(encoding="utf-8"))["version"]
    if version != "0.180.0":
        raise ValueError("Install the locked Three.js 0.180.0 dependency first")
    vendor = WEB / "vendor"
    vendor.mkdir(exist_ok=True)
    for source, target in [("build/three.module.min.js", "three.module.js"),
                           ("build/three.core.min.js", "three.core.min.js"),
                           ("LICENSE", "THREE-LICENSE.txt")]:
        (vendor / target).write_bytes((package / source).read_bytes())
    files = ["visual-assets.js", "visual-inventory.js", "visual-renderer.js", "visual-layers.js", "visual-board-scene.js",
             "vendor/three.module.js", "vendor/three.core.min.js", "vendor/THREE-LICENSE.txt"]
    # Match the scoped Git LF policy before hashing, including existing Windows
    # working copies created before that policy was added.
    for name in files:
        source = WEB / name
        source.write_bytes(source.read_bytes().replace(b"\r\n", b"\n"))
    hashes = {name: hashlib.sha256((WEB / name).read_bytes()).hexdigest() for name in files}
    value = json.dumps(hashes, sort_keys=True, separators=(",", ":"))
    fingerprint = hashlib.sha256(value.encode()).hexdigest()
    (WEB / "visual-version.js").write_text(
        "// Generated by scripts/prepare_visual_assets.py; changes invalidate visual manifests.\n"
        f"export const VISUAL_SOURCE_HASH = {json.dumps(fingerprint)};\n"
        f"export const VISUAL_FILE_HASHES = Object.freeze({json.dumps(hashes, indent=2)});\n",
        encoding="utf-8", newline="\n",
    )
    print(f"Three.js {version}; visual source SHA256 {fingerprint}")


if __name__ == "__main__":
    main()
